### ISSUE TITLE
Ошибка при Verify!

### ISSUE THREAD

**Issue by AutomationEngineerGaneev** [ArthurGaneev/CashbackService#7]
@coursar ,[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.293 s
[INFO] Finished at: 2019-01-12T18:34:48+03:00
[INFO] Final Memory: 24M/87M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.11.0:check (default) on project unit-coverage: You have 1 PMD violation. For more details see: C:\Users\Artur\IdeaProjects\CashbackService\target\pmd.xml -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Process finished with exit code 1

**Comment by coursar** [comment]
[INFO] PMD Failure: ru.itpark.CashbackService:10 Rule:UselessParentheses Priority:4 Useless parentheses..
